AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2"
Parameters:
  ImageId:
    Type: AWS::EC2::Image::Id
    Description: "Linux AMI"
Resources:
  JakeLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: JakeLaunchTemplate
      LaunchTemplateData:
        KeyName: JakeKey
        InstanceType: t2.micro
        ImageId: !Ref ImageId
        NetworkInterfaces: 
          - AssociatePublicIpAddress: true
            DeviceIndex: 0
            SubnetId: !ImportValue JakePublicSubnet
            Groups:
              - !ImportValue JakeSecGroupName

  UbuntuInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      LaunchTemplate: 
        LaunchTemplateId: !Ref JakeLaunchTemplate
        Version: "1"
      Tags:
        - Key: Name
          Value: "Jake-debian"

  launchConfigName:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref ImageId
      InstanceId: !Ref UbuntuInstance
      KeyName: JakeKey
      InstanceType: t2.medium
  
  AppScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref asg
      Cooldown: '60'
      ScalingAdjustment: 1

  AppScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref asg
      Cooldown: '300'
      ScalingAdjustment: -1
  
  CPUAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Scale-up if CPU > 80% for 5 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 120
      EvaluationPeriods: 2
      Threshold: 60
      AlarmActions: [!Ref AppScaleUpPolicy]
      Dimensions:
      - Name: AutoScalingGroupName
        Value: !Ref asg
      ComparisonOperator: GreaterThanThreshold

  CPUAlarmLow:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Scale-down if CPU < 60% for 5 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 120
      EvaluationPeriods: 2
      Threshold: 60
      AlarmActions: [!Ref AppScaleDownPolicy]
      Dimensions:
      - Name: AutoScalingGroupName
        Value: !Ref asg
      ComparisonOperator: LessThanThreshold

  asg:
    Type: AWS::AutoScaling::AutoScalingGroup
    UpdatePolicy:
        AutoScalingReplacingUpdate:
          WillReplace: true
    Properties:
      AvailabilityZones: 
        - 'us-east-1a'
      LaunchTemplate: 
        LaunchTemplateId: !Ref JakeLaunchTemplate
        Version: '1'
      VPCZoneIdentifier:
        - !ImportValue JakePublicSubnet
      MaxSize: "1"
      MinSize: "1"

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref UbuntuInstance

Outputs:
  EIP:
    Value: !Ref EIP