AWSTemplateFormatVersion: "2010-09-09"
Description: "Cross-Referencing Resources within a Template"

Parameters: 
  IAMName:
    Type: String
    Description: User Name
  IAMPolicyName:
    Type: String
    Description: Policy Name
    Default: "read-only"

Resources:
  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref IAMName
  IAMManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref IAMPolicyName
      Users:
       - !Ref IAMUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 's3:ListAllMyBuckets'
            Resource: 'arn:aws:s3:::*'
          - Effect: Allow
            Action:
              - 's3:GetObject'
            Resource: 'arn:aws:s3:::*'
Outputs:
  IAMPolicyResourceName: 
    Description: "Managed Policy's Amazon Resource Name"
    Value: !Ref IAMManagedPolicy
    Export:
      Name: JakeIAMPolicyResourceName