AWSTemplateFormatVersion: "2010-09-09"
Description: 'S3 bucket'
Parameters:
  BucketName:
    Type: String
    Description: 'Bucket Name'
    Default: 'jake-bucket'
  IAMUser:
    Type: String
    Description: Name of User to give Maintenance access to
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', [!Ref AWS::Region, !Ref AWS::AccountId, !Ref BucketName]]
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !Ref S3Key
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: "KeyName"
          Value: "value12"

      LifecycleConfiguration:
        Rules:
          - Id: StandardObjects
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
            NoncurrentVersionExpirationInDays: 7
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
  PublicReadBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
            Principal: '*'
            
  S3Key:
    Type: AWS::KMS::Key
    Properties:
      Enabled: true
      Description: Key
      KeyPolicy:
        Version: "2012-10-17"
        Id: 'jake-default-key'
        Statement:
        - Sid: Enable IAM policies
          Effect: Allow
          Principal:
            AWS: !Sub
              - arn:aws:iam::${AccountID}:user/${UserName}
              - { AccountID: !Ref AWS::AccountId, UserName: !Ref IAMUser }
          Action: kms:*
          Resource: "*"
  TheKeyAlias:
    Type: AWS::KMS::Alias
    Properties: 
      AliasName: alias/jake
      TargetKeyId: !Ref S3Key