AWSTemplateFormatVersion: 2010-09-09

Resources: 
    dynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties: 
          AttributeDefinitions: 
            - AttributeName: ID
              AttributeType: "S"
            - AttributeName: part
              AttributeType: "S"
          BillingMode: PAY_PER_REQUEST
          KeySchema: 
            - AttributeName: ID
              KeyType: HASH
            - AttributeName: part
              KeyType: RANGE
          TableName: Part

    MyAppExecutionRole:
      Type: AWS::IAM::Role
      Properties: 
        AssumeRolePolicyDocument:
           Version: 2012-10-17
           Statement:
           - Effect: Allow
             Principal:
                 Service: lambda.amazonaws.com
             Action: sts:AssumeRole
        ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        RoleName: jake-pipe-dynamo-app